spring:

  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    defer-datasource-initialization: false

  flyway:
    enabled: true
    baseline-on-migrate: true
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    user: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}

jwt:
  header: Authorization
  secret: ${JWT_SECRET}
  expires-in: 86400

logging:
  level:
    me.myeats: WARN
