spring:

  datasource:
    url: jdbc:mysql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: false

jwt:
  header: Authorization
  secret: ${JWT_SECRET}
  expires-in: 86400

logging:
  level:
    me.myeats: DEBUG

server:
  port: 5000
